#!/bin/bash

#clone into applications
cd /applications/
unset GIT_DIR
rm -rf food-information-ui
git clone /applications/food-information-ui.git
echo '✓ Cloned repository'

#install dependencies
cd /applications/food-information-ui
yarn build
echo '✓ Installed dependencies'

